FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# hadiyanto

Polls is a simple API allowing consumers to view polls and vote in them.

## Payment [/v3/payment/ex/direct]

### Get Payment List [GET]

+ Request with complete header
    + Headers

            Authorization: 'uDNTl8RWo6K2yQv6PHjSyvjwt518UZJ99ecXa2Ag'
            Chennel: 'MOBILE'
            
+ Response 200 (application/json)

        [
            {
                "code": 1000,
                "message": {
                    "notification": "Untuk total biaya di atas 1 juta, kamu mempunyai opsi pembayaran melalui metode pembayaran di bawah",
                    "payment_method": {
                        "title": "Bayar melalui bank",
                        "list_bank": [
                            {
                                "id": 1,
                                "icon": "https://dev-static.kudo.co.id/api/images/direct/bca-1513844841.png",
                                "name": "BCA",
                                "maintenance": 0,
                                "description": [
                                    "Pembayaran dapat dilakukan dengan melalui transfer ke nomor Virtual Account yang akan diberikan di halaman selanjutnya",
                                    "Nomor Virtual Account hanya berlaku per 1 kali transaksi"
                                ]
                            },
                            {
                                "id": 2,
                                "icon": "https://dev-static.kudo.co.id/api/images/direct/mandiri-1513053847.png",
                                "name": "Mandiri",
                                "maintenance": 0,
                                "description": [
                                    "Pembayaran dapat dilakukan dengan melalui transfer ke nomor Virtual Account yang akan diberikan di halaman selanjutnya",
                                    "Nomor Virtual Account hanya berlaku per 1 kali transaksi"
                                ]
                            },
                            {
                                "id": 3,
                                "icon": "https://dev-static.kudo.co.id/api/images/direct/permata-1513053872.png",
                                "name": "Permata",
                                "maintenance": 0,
                                "description": [
                                    "Pembayaran dapat dilakukan dengan melalui transfer ke nomor Virtual Account yang akan diberikan di halaman selanjutnya",
                                    "Nomor Virtual Account hanya berlaku per 1 kali transaksi"
                                ]
                            },
                            {
                                "id": 4,
                                "icon": "https://dev-static.kudo.co.id/api/images/direct/bri-1513053896.png",
                                "name": "BRI",
                                "maintenance": 0,
                                "description": [
                                    "Pembayaran dapat dilakukan dengan melalui transfer ke nomor Virtual Account yang akan diberikan di halaman selanjutnya",
                                    "Nomor Virtual Account hanya berlaku per 1 kali transaksi"
                                ]
                            },
                            {
                                "id": 5,
                                "icon": "https://dev-static.kudo.co.id/api/images/direct/danamon-1513053908.png",
                                "name": "Danamon",
                                "maintenance": 0,
                                "description": [
                                    "Pembayaran dapat dilakukan dengan melalui transfer ke nomor Virtual Account yang akan diberikan di halaman selanjutnya",
                                    "Nomor Virtual Account hanya berlaku per 1 kali transaksi"
                                ]
                            },
                            {
                                "id": 6,
                                "icon": "https://dev-static.kudo.co.id/api/images/direct/bank_lainnya-1512918414.png",
                                "name": "Bank Lainnya",
                                "maintenance": 0,
                                "description": [
                                    "Untuk pembayaran melalui bank lain akan dikenakan biaya transfer antar bank sebesar Rp 6,500",
                                    "Pembayaran dapat dilakukan dengan melalui transfer ke nomor Virtual Account yang akan diberikan di halaman selanjutnya",
                                    "Nomor Virtual Account hanya berlaku per 1 kali transaksi"
                                ]
                            }
                        ]
                    }
                }
            }
        ]
        
+ Request Without Header Authorization
    + Headers

            Chennel: 'MOBILE'
                
+ Response 401 (application/json)

        [
            {
                "code": 2005,
                "message": "Not Authorized"
            }
        ]
        
+ Request Without Header Channel
    + Headers

            Authorization: 'uDNTl8RWo6K2yQv6PHjSyvjwt518UZJ99ecXa2Ag'
               
+ Response 401 (application/json)

        [
            {
                "code": 2005,
                "message": "Not Authorized"
            }
        ]